# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jan's Place
email: j.halozan.services@gmail.com
description: > Personal portfolio and blog for Jan Halozan,
    an independent iOS developer based in Slovenia. Also a tech head
    and computer science freak.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://janhalozan.com" # the base hostname & protocol for your site
twitter_username: janhalozan
github_username:  JanHalozan

# Build settings
markdown: kramdown
